const db = require('./database');

const LEGACY_CONFIG_TABLES = Object.freeze([
  ['settings', 'settings_legacy_archive'],
  ['bot_presence_settings', 'bot_presence_settings_legacy_archive'],
]);
const RETIRED_RUNTIME_TABLES = Object.freeze([
  'weekly_staff_events',
  'weekly_staff_scores',
  'weekly_staff_winners',
  'weekly_staff_config',
  'message_templates',
  'moderation_rate_limits',
]);
const PRIVATE_VOICE_ROOM_OPTIONAL_COLUMNS = Object.freeze([
  ['lock_snapshot_json', 'TEXT'],
  ['visibility_snapshot_json', 'TEXT NULL'],
  ['permit_role_ids_json', "TEXT NOT NULL DEFAULT '[]'"],
  ['reject_member_ids_json', "TEXT NOT NULL DEFAULT '[]'"],
  ['reject_role_ids_json', "TEXT NOT NULL DEFAULT '[]'"],
]);

async function safeExecute(sql, params = [], logError = () => {}) {
  try {
    await db.execute(sql, params);
  } catch (err) {
    logError('postgres_schema_query_failed', err, { sql: String(sql).slice(0, 180) });
    throw err;
  }
}

async function safeCleanup(sql, params = [], logError = () => {}) {
  try {
    await db.execute(sql, params);
  } catch (err) {
    logError('postgres_schema_cleanup_failed', err, { sql: String(sql).slice(0, 180) });
  }
}

function quoteIdentifier(value) {
  return `"${String(value || '').replace(/"/g, '""')}"`;
}

async function tableExists(tableName) {
  const [rows] = await db.execute(
    `
      SELECT EXISTS (
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = current_schema()
          AND table_name = ?
      ) AS exists
    `,
    [tableName]
  );
  return rows?.[0]?.exists === true;
}

async function archiveLegacyTable(activeName, archiveName, logSystem = () => {}, logError = () => {}) {
  const activeExists = await tableExists(activeName);
  if (!activeExists) return;

  const archiveExists = await tableExists(archiveName);
  if (!archiveExists) {
    await safeExecute(
      `ALTER TABLE ${quoteIdentifier(activeName)} RENAME TO ${quoteIdentifier(archiveName)}`,
      [],
      logError
    );
    logSystem(`Legacy config table archived: ${activeName} -> ${archiveName}`, 'WARN');
    return;
  }

  await safeCleanup(`DROP TABLE IF EXISTS ${quoteIdentifier(activeName)}`, [], logError);
  logSystem(`Legacy config table dropped after archive confirmation: ${activeName}`, 'WARN');
}

async function ensureOptionalColumns(tableName, columns = [], logError = () => {}) {
  for (const [columnName, columnType] of columns) {
    await safeExecute(
      `ALTER TABLE ${quoteIdentifier(tableName)} ADD COLUMN IF NOT EXISTS ${quoteIdentifier(columnName)} ${columnType}`,
      [],
      logError
    );
  }
}

async function dropRetiredTables(logError = () => {}) {
  for (const tableName of RETIRED_RUNTIME_TABLES) {
    await safeCleanup(`DROP TABLE IF EXISTS ${quoteIdentifier(tableName)}`, [], logError);
  }
}

async function ensurePostgresStartupSchema(logSystem = () => {}, logError = () => {}) {
  for (const [activeName, archiveName] of LEGACY_CONFIG_TABLES) {
    await archiveLegacyTable(activeName, archiveName, logSystem, logError);
  }

  await safeExecute(
    `CREATE TABLE IF NOT EXISTS mod_logs (
      id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      guild_id     VARCHAR(32)  NOT NULL,
      user_id      VARCHAR(32)  NOT NULL,
      moderator_id VARCHAR(32)  NOT NULL,
      action_type  VARCHAR(32)  NOT NULL,
      reason       VARCHAR(255) NOT NULL DEFAULT 'Yok',
      duration     VARCHAR(32)  NOT NULL DEFAULT 'Yok',
      created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    [],
    logError
  );
  await safeExecute(
    'CREATE INDEX IF NOT EXISTS idx_mod_logs_guild_user_id ON mod_logs (guild_id, user_id, id)',
    [],
    logError
  );
  await safeExecute(
    'CREATE INDEX IF NOT EXISTS idx_mod_logs_guild_action_created ON mod_logs (guild_id, action_type, created_at)',
    [],
    logError
  );

  await safeExecute(
    `CREATE TABLE IF NOT EXISTS timed_penalties (
      id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      guild_id    VARCHAR(32) NOT NULL,
      user_id     VARCHAR(32) NOT NULL,
      action_type VARCHAR(16) NOT NULL,
      role_id     VARCHAR(32) NULL,
      revoke_at   BIGINT      NOT NULL,
      reason      VARCHAR(255) NULL,
      active      BOOLEAN     NOT NULL DEFAULT TRUE,
      created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
      revoked_at  BIGINT      NULL
    )`,
    [],
    logError
  );
  await safeExecute(
    'CREATE INDEX IF NOT EXISTS idx_tp_active_revoke ON timed_penalties (active, revoke_at)',
    [],
    logError
  );
  await safeExecute(
    'CREATE INDEX IF NOT EXISTS idx_tp_lookup ON timed_penalties (guild_id, user_id, action_type, active)',
    [],
    logError
  );
  await safeExecute(
    `WITH ranked AS (
       SELECT id,
              ROW_NUMBER() OVER (
                PARTITION BY guild_id, user_id, action_type
                ORDER BY revoke_at DESC, id DESC
              ) AS rn
       FROM timed_penalties
       WHERE active = TRUE
     )
     UPDATE timed_penalties AS tp
        SET active = FALSE,
            revoked_at = COALESCE(tp.revoked_at, ?)
      WHERE tp.id IN (
        SELECT id
        FROM ranked
        WHERE rn > 1
      )`,
    [Date.now()],
    logError
  );
  await safeExecute(
    'CREATE UNIQUE INDEX IF NOT EXISTS uq_timed_penalties_active_unique ON timed_penalties (guild_id, user_id, action_type) WHERE active = TRUE',
    [],
    logError
  );

  await safeExecute(
    `CREATE TABLE IF NOT EXISTS timed_penalty_role_snapshots (
      guild_id   VARCHAR(32) NOT NULL,
      user_id    VARCHAR(32) NOT NULL,
      roles_json TEXT        NOT NULL,
      updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (guild_id, user_id)
    )`,
    [],
    logError
  );

  await safeExecute(
    `CREATE TABLE IF NOT EXISTS reaction_rules (
      id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      guild_id           VARCHAR(32)  NOT NULL,
      channel_id         VARCHAR(32)  NOT NULL,
      message_id         VARCHAR(32)  NOT NULL,
      emoji_type         VARCHAR(16)  NOT NULL,
      emoji_id           VARCHAR(64)  NULL,
      emoji_name         VARCHAR(128) NULL,
      trigger_mode       VARCHAR(16)  NOT NULL DEFAULT 'TOGGLE',
      enabled            BOOLEAN      NOT NULL DEFAULT TRUE,
      cooldown_seconds   INTEGER      NOT NULL DEFAULT 5,
      only_once          BOOLEAN      NOT NULL DEFAULT FALSE,
      group_key          VARCHAR(64)  NULL,
      allowed_roles_json TEXT         NULL,
      excluded_roles_json TEXT        NULL,
      actions_json       TEXT         NOT NULL DEFAULT '[]',
      created_by         VARCHAR(32)  NULL,
      created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    [],
    logError
  );
  await safeExecute(
    'CREATE INDEX IF NOT EXISTS idx_rr_guild_enabled ON reaction_rules (guild_id, enabled)',
    [],
    logError
  );
  await safeExecute(
    'CREATE INDEX IF NOT EXISTS idx_rr_lookup ON reaction_rules (guild_id, message_id, emoji_type, emoji_id, emoji_name)',
    [],
    logError
  );

  await safeExecute(
    `CREATE TABLE IF NOT EXISTS reaction_rule_logs (
      id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      guild_id      VARCHAR(32) NOT NULL,
      rule_id       BIGINT      NOT NULL,
      user_id       VARCHAR(32) NOT NULL,
      event_type    VARCHAR(16) NOT NULL,
      status        VARCHAR(16) NOT NULL,
      action_type   VARCHAR(32) NULL,
      error_code    VARCHAR(64) NULL,
      error_message VARCHAR(255) NULL,
      created_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    [],
    logError
  );
  await safeExecute(
    'CREATE INDEX IF NOT EXISTS idx_rrl_rule_time ON reaction_rule_logs (rule_id, created_at)',
    [],
    logError
  );
  await safeExecute(
    'CREATE INDEX IF NOT EXISTS idx_rrl_guild_time ON reaction_rule_logs (guild_id, created_at)',
    [],
    logError
  );
  await safeExecute(
    `CREATE TABLE IF NOT EXISTS reaction_rule_only_once_executions (
      rule_id     BIGINT      NOT NULL,
      guild_id    VARCHAR(32) NOT NULL,
      user_id     VARCHAR(32) NOT NULL,
      event_type  VARCHAR(16) NOT NULL,
      state       VARCHAR(16) NOT NULL DEFAULT 'PENDING',
      created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (rule_id, user_id, event_type)
    )`,
    [],
    logError
  );
  await safeExecute(
    'CREATE INDEX IF NOT EXISTS idx_rroo_guild_state ON reaction_rule_only_once_executions (guild_id, state, updated_at)',
    [],
    logError
  );

  await safeExecute(
    `CREATE TABLE IF NOT EXISTS private_voice_rooms (
      id                       BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      guild_id                 VARCHAR(32) NOT NULL,
      owner_id                 VARCHAR(32) NOT NULL,
      voice_channel_id         VARCHAR(32) NOT NULL,
      panel_message_id         VARCHAR(32) NULL,
      locked                   BOOLEAN     NOT NULL DEFAULT FALSE,
      lock_snapshot_json       TEXT        NULL,
      visibility_snapshot_json TEXT        NULL,
      whitelist_member_ids_json TEXT       NOT NULL DEFAULT '[]',
      permit_role_ids_json     TEXT        NOT NULL DEFAULT '[]',
      reject_member_ids_json   TEXT        NOT NULL DEFAULT '[]',
      reject_role_ids_json     TEXT        NOT NULL DEFAULT '[]',
      last_active_at           BIGINT      NOT NULL,
      created_at               TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at               TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT uq_private_room_owner UNIQUE (guild_id, owner_id),
      CONSTRAINT uq_private_room_channel UNIQUE (guild_id, voice_channel_id)
    )`,
    [],
    logError
  );
  await safeExecute(
    'CREATE INDEX IF NOT EXISTS idx_private_room_last_active ON private_voice_rooms (last_active_at)',
    [],
    logError
  );
  await ensureOptionalColumns('private_voice_rooms', PRIVATE_VOICE_ROOM_OPTIONAL_COLUMNS, logError);

  await safeExecute(
    `CREATE TABLE IF NOT EXISTS text_channel_lock_snapshots (
      guild_id         VARCHAR(32) NOT NULL,
      channel_id       VARCHAR(32) NOT NULL,
      everyone_role_id VARCHAR(32) NOT NULL,
      snapshot_json    TEXT        NOT NULL,
      created_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (guild_id, channel_id)
    )`,
    [],
    logError
  );
  await safeExecute(
    'CREATE INDEX IF NOT EXISTS idx_text_channel_lock_snapshots_updated_at ON text_channel_lock_snapshots (updated_at)',
    [],
    logError
  );

  await safeExecute(
    `CREATE TABLE IF NOT EXISTS custom_commands (
      id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      guild_id         VARCHAR(32)  NOT NULL,
      command_name     VARCHAR(32)  NOT NULL,
      command_response VARCHAR(500) NOT NULL,
      created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT uq_custom_commands_guild_command UNIQUE (guild_id, command_name)
    )`,
    [],
    logError
  );
  await safeExecute(
    'CREATE INDEX IF NOT EXISTS idx_custom_commands_guild ON custom_commands (guild_id)',
    [],
    logError
  );

  await safeExecute(
    `CREATE TABLE IF NOT EXISTS custom_command_audit (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      guild_id VARCHAR(32) NOT NULL,
      command_name VARCHAR(32) NOT NULL,
      action_type VARCHAR(16) NOT NULL,
      actor_user_id VARCHAR(32) NULL,
      note VARCHAR(255) NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    [],
    logError
  );
  await safeExecute(
    'CREATE INDEX IF NOT EXISTS idx_custom_command_audit_guild_command_created ON custom_command_audit (guild_id, command_name, created_at)',
    [],
    logError
  );
  await safeExecute(
    'CREATE INDEX IF NOT EXISTS idx_custom_command_audit_actor_created ON custom_command_audit (actor_user_id, created_at)',
    [],
    logError
  );

  await safeExecute(
    `CREATE TABLE IF NOT EXISTS private_voice_room_logs (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      room_id BIGINT NOT NULL,
      guild_id VARCHAR(32) NOT NULL,
      owner_id VARCHAR(32) NOT NULL,
      action_type VARCHAR(64) NOT NULL,
      target_user_id VARCHAR(32) NULL,
      metadata_json TEXT NULL,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    [],
    logError
  );

  await safeExecute(
    'CREATE INDEX IF NOT EXISTS idx_pvrl_room_time ON private_voice_room_logs (room_id, created_at)',
    [],
    logError
  );
  await safeExecute(
    'CREATE INDEX IF NOT EXISTS idx_pvrl_guild_owner_time ON private_voice_room_logs (guild_id, owner_id, created_at)',
    [],
    logError
  );
  await dropRetiredTables(logError);

  logSystem('PostgreSQL startup schema hazir: runtime state + audit tables', 'INFO');
}

module.exports = {
  ensurePostgresStartupSchema,
};
