-- PostgreSQL P0 schema
-- Source of truth: current runtime state + audit table set.
-- Static infrastructure/policy config is intentionally excluded from this baseline kit.

BEGIN;

CREATE SCHEMA IF NOT EXISTS public;

CREATE OR REPLACE FUNCTION public.pg_p0_json_valid(input_text text)
RETURNS boolean
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
  PERFORM input_text::jsonb;
  RETURN true;
EXCEPTION WHEN others THEN
  RETURN false;
END;
$$;

CREATE OR REPLACE FUNCTION public.pg_p0_touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.mod_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id varchar(32) NOT NULL,
  user_id varchar(32) NOT NULL,
  moderator_id varchar(32) NOT NULL,
  action_type varchar(32) NOT NULL,
  reason varchar(255) NOT NULL DEFAULT 'Yok',
  duration varchar(32) NOT NULL DEFAULT 'Yok',
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_mod_logs_guild_user_id
  ON public.mod_logs (guild_id, user_id, id);
CREATE INDEX IF NOT EXISTS idx_mod_logs_guild_action_created
  ON public.mod_logs (guild_id, action_type, created_at);

CREATE TABLE IF NOT EXISTS public.timed_penalties (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id varchar(32) NOT NULL,
  user_id varchar(32) NOT NULL,
  action_type varchar(16) NOT NULL,
  role_id varchar(32),
  revoke_at bigint NOT NULL,
  reason varchar(255),
  active boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revoked_at bigint
);

CREATE INDEX IF NOT EXISTS idx_tp_active_revoke
  ON public.timed_penalties (active, revoke_at);
CREATE INDEX IF NOT EXISTS idx_tp_lookup
  ON public.timed_penalties (guild_id, user_id, action_type, active);
CREATE UNIQUE INDEX IF NOT EXISTS uq_timed_penalties_active_unique
  ON public.timed_penalties (guild_id, user_id, action_type)
  WHERE active = TRUE;

CREATE TABLE IF NOT EXISTS public.timed_penalty_role_snapshots (
  guild_id varchar(32) NOT NULL,
  user_id varchar(32) NOT NULL,
  roles_json text NOT NULL,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (guild_id, user_id)
);

DROP TRIGGER IF EXISTS trg_tprs_touch_updated_at ON public.timed_penalty_role_snapshots;
CREATE TRIGGER trg_tprs_touch_updated_at
BEFORE UPDATE ON public.timed_penalty_role_snapshots
FOR EACH ROW
EXECUTE FUNCTION public.pg_p0_touch_updated_at();

CREATE TABLE IF NOT EXISTS public.reaction_rules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id varchar(32) NOT NULL,
  channel_id varchar(32) NOT NULL,
  message_id varchar(32) NOT NULL,
  emoji_type varchar(16) NOT NULL,
  emoji_id varchar(64),
  emoji_name varchar(128),
  trigger_mode varchar(16) NOT NULL DEFAULT 'TOGGLE',
  enabled boolean NOT NULL DEFAULT true,
  cooldown_seconds integer NOT NULL DEFAULT 5,
  only_once boolean NOT NULL DEFAULT false,
  group_key varchar(64),
  allowed_roles_json text,
  excluded_roles_json text,
  actions_json text NOT NULL DEFAULT '[]',
  created_by varchar(32),
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_rr_allowed_roles_json CHECK (allowed_roles_json IS NULL OR public.pg_p0_json_valid(allowed_roles_json)),
  CONSTRAINT ck_rr_excluded_roles_json CHECK (excluded_roles_json IS NULL OR public.pg_p0_json_valid(excluded_roles_json)),
  CONSTRAINT ck_rr_actions_json CHECK (public.pg_p0_json_valid(actions_json))
);

CREATE INDEX IF NOT EXISTS idx_rr_guild_enabled
  ON public.reaction_rules (guild_id, enabled);
CREATE INDEX IF NOT EXISTS idx_rr_lookup
  ON public.reaction_rules (guild_id, message_id, emoji_type, emoji_id, emoji_name);

DROP TRIGGER IF EXISTS trg_reaction_rules_touch_updated_at ON public.reaction_rules;
CREATE TRIGGER trg_reaction_rules_touch_updated_at
BEFORE UPDATE ON public.reaction_rules
FOR EACH ROW
EXECUTE FUNCTION public.pg_p0_touch_updated_at();

CREATE TABLE IF NOT EXISTS public.reaction_rule_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id varchar(32) NOT NULL,
  rule_id bigint NOT NULL,
  user_id varchar(32) NOT NULL,
  event_type varchar(16) NOT NULL,
  status varchar(16) NOT NULL,
  action_type varchar(32),
  error_code varchar(64),
  error_message varchar(255),
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_rrl_rule_time
  ON public.reaction_rule_logs (rule_id, created_at);
CREATE INDEX IF NOT EXISTS idx_rrl_guild_time
  ON public.reaction_rule_logs (guild_id, created_at);

CREATE TABLE IF NOT EXISTS public.reaction_rule_only_once_executions (
  rule_id bigint NOT NULL,
  guild_id varchar(32) NOT NULL,
  user_id varchar(32) NOT NULL,
  event_type varchar(16) NOT NULL,
  state varchar(16) NOT NULL DEFAULT 'PENDING',
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (rule_id, user_id, event_type)
);

CREATE INDEX IF NOT EXISTS idx_rroo_guild_state
  ON public.reaction_rule_only_once_executions (guild_id, state, updated_at);

DROP TRIGGER IF EXISTS trg_reaction_rule_only_once_touch_updated_at ON public.reaction_rule_only_once_executions;
CREATE TRIGGER trg_reaction_rule_only_once_touch_updated_at
BEFORE UPDATE ON public.reaction_rule_only_once_executions
FOR EACH ROW
EXECUTE FUNCTION public.pg_p0_touch_updated_at();

CREATE TABLE IF NOT EXISTS public.private_voice_rooms (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id varchar(32) NOT NULL,
  owner_id varchar(32) NOT NULL,
  voice_channel_id varchar(32) NOT NULL,
  panel_message_id varchar(32),
  locked boolean NOT NULL DEFAULT false,
  lock_snapshot_json text,
  visibility_snapshot_json text,
  whitelist_member_ids_json text NOT NULL DEFAULT '[]',
  last_active_at bigint NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_private_room_owner UNIQUE (guild_id, owner_id),
  CONSTRAINT uq_private_room_channel UNIQUE (guild_id, voice_channel_id),
  CONSTRAINT ck_private_room_whitelist_json CHECK (public.pg_p0_json_valid(whitelist_member_ids_json))
);

CREATE INDEX IF NOT EXISTS idx_private_room_last_active
  ON public.private_voice_rooms (last_active_at);

DROP TRIGGER IF EXISTS trg_private_voice_rooms_touch_updated_at ON public.private_voice_rooms;
CREATE TRIGGER trg_private_voice_rooms_touch_updated_at
BEFORE UPDATE ON public.private_voice_rooms
FOR EACH ROW
EXECUTE FUNCTION public.pg_p0_touch_updated_at();

CREATE TABLE IF NOT EXISTS public.text_channel_lock_snapshots (
  guild_id varchar(32) NOT NULL,
  channel_id varchar(32) NOT NULL,
  everyone_role_id varchar(32) NOT NULL,
  snapshot_json text NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (guild_id, channel_id),
  CONSTRAINT ck_text_channel_lock_snapshot_json CHECK (public.pg_p0_json_valid(snapshot_json))
);

CREATE INDEX IF NOT EXISTS idx_text_channel_lock_snapshots_updated_at
  ON public.text_channel_lock_snapshots (updated_at);

DROP TRIGGER IF EXISTS trg_text_channel_lock_snapshots_touch_updated_at ON public.text_channel_lock_snapshots;
CREATE TRIGGER trg_text_channel_lock_snapshots_touch_updated_at
BEFORE UPDATE ON public.text_channel_lock_snapshots
FOR EACH ROW
EXECUTE FUNCTION public.pg_p0_touch_updated_at();

CREATE TABLE IF NOT EXISTS public.custom_commands (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id varchar(32) NOT NULL,
  command_name varchar(32) NOT NULL,
  command_response varchar(500) NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_custom_commands_guild_command UNIQUE (guild_id, command_name)
);

CREATE INDEX IF NOT EXISTS idx_custom_commands_guild
  ON public.custom_commands (guild_id);

DROP TRIGGER IF EXISTS trg_custom_commands_touch_updated_at ON public.custom_commands;
CREATE TRIGGER trg_custom_commands_touch_updated_at
BEFORE UPDATE ON public.custom_commands
FOR EACH ROW
EXECUTE FUNCTION public.pg_p0_touch_updated_at();

CREATE TABLE IF NOT EXISTS public.custom_command_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id varchar(32) NOT NULL,
  command_name varchar(32) NOT NULL,
  action_type varchar(16) NOT NULL,
  actor_user_id varchar(32),
  note varchar(255),
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_custom_command_audit_guild_command_created
  ON public.custom_command_audit (guild_id, command_name, created_at);
CREATE INDEX IF NOT EXISTS idx_custom_command_audit_actor_created
  ON public.custom_command_audit (actor_user_id, created_at);

CREATE TABLE IF NOT EXISTS public.private_voice_room_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id bigint NOT NULL,
  guild_id varchar(32) NOT NULL,
  owner_id varchar(32) NOT NULL,
  action_type varchar(64) NOT NULL,
  target_user_id varchar(32),
  metadata_json text,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ck_private_voice_room_logs_metadata_json CHECK (metadata_json IS NULL OR public.pg_p0_json_valid(metadata_json))
);

CREATE INDEX IF NOT EXISTS idx_pvrl_room_time
  ON public.private_voice_room_logs (room_id, created_at);
CREATE INDEX IF NOT EXISTS idx_pvrl_guild_owner_time
  ON public.private_voice_room_logs (guild_id, owner_id, created_at);

COMMIT;
